### ISSUE TITLE
Crashes on `veriff.startAuthentication(sessionUrl:configuration:)` when app switches background/foreground state

### ISSUE THREAD

**Issue by dterekhov** [Veriff/veriff-ios-spm#2]
Please fix it! Can't reproduce it personally but our users periodically get such reports. Crashes on calling
```
let veriff = VeriffSdk.shared
veriff.delegate = self
veriff.startAuthentication(sessionUrl: url, configuration: configuration)
```
Usually along with when the app goes in background/foreground state. Two screenshots of the same crash from Xcode Organizer + Firebase Crashlytics.
<img width="991" alt="Screenshot 2023-02-22 at 4 31 15 PM" src="https://user-images.githubusercontent.com/9823122/220635005-106fb83c-a66c-4f28-81e4-32bc566d050e.png">
<img width="978" alt="Screenshot 2023-02-22 at 4 31 44 PM" src="https://user-images.githubusercontent.com/9823122/220635029-a527d241-b7f0-4e38-9481-5d663f340a8b.png">

**Comment by MertCelik** [comment]
Hey @dterekhov!

We do not follow issues in this repository, could you please reach us from [support@veriff.com](mailto:support@veriff.com)?

(we noted this issue)
